namespace ConsoleApp;

using Microsoft.Extensions.VectorData;

/// <summary>
/// Represents a product in the vector store with embeddings.
/// </summary>
public class ProductRecord
{
    /// <summary>
    /// The unique identifier for the product.
    /// </summary>
    [VectorStoreKey]
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// The product name.
    /// </summary>
    [VectorStoreData(IsIndexed = true)]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// The product description.
    /// This field will be used to automatically generate the DescriptionEmbedding vector.
    /// </summary>
    [VectorStoreData]
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// The product category.
    /// </summary>
    [VectorStoreData(IsIndexed = true)]
    public string Category { get; set; } = string.Empty;

    /// <summary>
    /// The product price.
    /// </summary>
    [VectorStoreData(IsIndexed = true)]
    public decimal Price { get; set; }

    /// <summary>
    /// Vector embedding of the product description.
    /// This will be automatically generated by the VoyageAI embedding generator from the Description property.
    /// Needs to be a string in order for the embedding generator to automatically use the IEmbeddingGenerator to create the embedding.
    /// </summary>
    [VectorStoreVector(Dimensions: 1024, DistanceFunction = DistanceFunction.CosineSimilarity, IndexKind = IndexKind.Hnsw)]
    public string? DescriptionEmbedding => Description;
}
